apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-library-ingress
  namespace: mayar
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: library-app-service
            port:
              number: 80

