apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app-deployment
  namespace: team6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app:  library-app
    spec:
      containers:
        - name: library-app
          image: mayaremam/library_app:latest 
          imagePullPolicy: Always 
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: library-db-storage
              mountPath: /app/instance
      volumes:
        - name: library-db-storage
          persistentVolumeClaim:
            claimName: library-app-pvc  

              
              
