groups:
- name: library-app-prometheus-alerts
  rules:
  - alert: HighCPUUsage
    expr: rate(container_cpu_usage_seconds_total[5m]) > 0.9
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High CPU usage detected"
