apiVersion: v1
kind: Service
metadata:
  name: library-app-service-prometheus
  namespace: team6
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: library-app-prometheus
